# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - wget --no-check-certificate https://download.open-mpi.org/release/open-mpi/v3.0/openmpi-3.0.0.tar.gz
  - tar -zxf openmpi-3.0.0.tar.gz
  - pushd openmpi-3.0.0 && ./configure --prefix=$HOME/openmpi3 && make all install && popd
  - export PATH=$HOME/openmpi3/bin:$PATH