# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache:
  - packages: true
  - directories:
    - /usr/openmpi3

before_install:
  - ./install-ompi3.sh
  - export PATH=/usr/openmpi3/bin:$PATH