# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

sudo: false

env: OMPI_DIR="$(dirname $TRAVIS_BUILD_DIR)/openmpi3"

cache: packages

before_install:
  - ./install-ompi3.sh
  - export PATH=$OMPI_DIR/bin:$PATH