# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  - packages: true
  - directories:
    - /home/travis/build/nbenn/openmpi3

before_install:
  - ./install-ompi3.sh
  - export PATH=/home/travis/build/nbenn/openmpi3/bin:$PATH