# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hello world
#'
#' Simple function using Rcpp
#' 
#' @export
rcpp_hello_world <- function() {
    .Call(`_rmpi3_rcpp_hello_world`)
}

#' Hello
#'
#' Simple function using Rcpp modules
#'
#' @name hello
#' 
NULL

