# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hello
#'
#' Simple function using Rcpp modules
#'
#' @name init
#' @export
#'
NULL

#' @name finalize
#' @rdname init
#' @export
NULL

#' @name get_world_size
#' @rdname init
#' @export
NULL

#' @name get_world_rank
#' @rdname init
#' @export
NULL

